export const POLICIES = {
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_VIEW_SELF: "USER_VIEW_SELF",
  USER_DELETE: "USER_DELETE",

  SINHVIEN_VIEW_ALL: "SINHVIEN:VIEW_ALL", // Xem danh sách
  SINHVIEN_VIEW_ONE: "SINHVIEN:VIEW_ONE", // Xem chi tiết theo mã
  SINHVIEN_CREATE:   "SINHVIEN:CREATE",   // Thêm
  SINHVIEN_UPDATE:   "SINHVIEN:UPDATE",   // Sửa
  SINHVIEN_DELETE:   "SINHVIEN:DELETE",   // Xóa


  // ---  QUYỀN CHO LỚP HỌC ---
  LOPHOC_VIEW_ALL: "LOPHOC:VIEW_ALL",
  LOPHOC_VIEW_ONE: "LOPHOC:VIEW_ONE",
  LOPHOC_CREATE:   "LOPHOC:CREATE",
  LOPHOC_UPDATE:   "LOPHOC:UPDATE",
  LOPHOC_DELETE:   "LOPHOC:DELETE",

  // --- QUYỀN CHO GIÁO VIÊN ---
  GIAOVIEN_VIEW_ALL: "GIAOVIEN:VIEW_ALL",
  GIAOVIEN_VIEW_ONE: "GIAOVIEN:VIEW_ONE",
  GIAOVIEN_CREATE:   "GIAOVIEN:CREATE",
  GIAOVIEN_UPDATE:   "GIAOVIEN:UPDATE",
  GIAOVIEN_DELETE:   "GIAOVIEN:DELETE",
};
